### ISSUE TITLE
IPNS integration

### ISSUE THREAD

**Issue by aroemers** [pfrazee/beaker#49]
Maybe I am missing something, or doing it wrong, but IPNS integration does not work (yet?). For instance, an URL like: `ipfs://ipns/dist.ipfs.io`

**Comment by pfrazee** [comment]
Correct, it's not yet integrated. I'm going to try to hit that by... oh, next Wednesday. Maybe even today.

**Comment by pfrazee** [comment]
Currently held up by an upstream issue: https://github.com/ipfs/go-ipfs/issues/3080

**Comment by pfrazee** [comment]
Upstream issue solved. Just need to add DNS support now.

**Comment by pfrazee** [comment]
IPNS is now supported, using pubkeys and DNS entries as the labels. Published in beaker-plugin-ipfs@1.1.0, and will be included by default in Beaker 0.2.0.

**Comment by aroemers** [comment]
Super! Thank you for this, and quick as well.

**Comment by pfrazee** [comment]
Sure thing. Shout out to the IPFS guys for their help
