### ISSUE TITLE
Errors in Debian 8

### ISSUE THREAD

**Issue by pfrazee** [pfrazee/beaker#62]
Reported by jakobvarmose in `#ipfs`

https://gist.github.com/jakobvarmose/6d4a204ecbddea9d7cc51ba7a9d8c644
https://gist.github.com/jakobvarmose/769a0e0b6986d2b037fe5a67620794fd

IPFS links failed to load, and then this error occurred.

Debian 8. npm v3.10.3. node v6.3.0

**Comment by jakobvarmose** [comment]
I tried the solution from here: http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc

But this didn't solve the problem.

**Comment by pfrazee** [comment]
@jakobvarmose I'm going to update `npm start` to disable the live-building, which is why FS watching is being invoked. Will update you when that's committed to master.

**Comment by pfrazee** [comment]
@jakobvarmose ok, give latest master a shot. Live-building is removed

**Comment by jakobvarmose** [comment]
I still have the same problems.

I deleted the ~/.ipfs folder before running beaker but no ~/.ipfs folder was created, and ipfs links don't work.

**Comment by pfrazee** [comment]
@jakobvarmose ok but it *is* running again, yes? I think we had a second problem start while diagnosing the IPFS problem.

**Comment by pfrazee** [comment]
if it is running, what does the CLI say about the IPFS daemon starting? Does it ever say it started, and spit out a version?

**Comment by jakobvarmose** [comment]
IPFS is not running. This is the output I get from beaker: 

```
> @ start /home/i/beaker
> gulp start

(node:15968) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[18:24:11] Using gulpfile ~/beaker/gulpfile.js
[18:24:11] Starting 'start'...
[18:24:11] Finished 'start' after 4.96 ms
Opening beaker:shell-window
[Web API] Denying permission request for openExternal for beaker:start
[Web API] Denying permission request for openExternal for beaker:start
[Web API] Denying permission request for openExternal for beaker:start
```

The `[Web API] ...` is printed each time I try to visit an ipfs url.

**Comment by pfrazee** [comment]
@jakobvarmose aha. The IPFS plugin isn't running, and I know why! A recent change broke the default installs for plugins.

Go to the settings page, in Beaker. You'll see a tool to install plugins. Search for the IPFS plugin, and install it.

If that fails (and let me know if it does!) you can copy/paste the "User data" path in the settings page, under "Application Info". CD into that directory, then run `npm install beaker-plugin-ipfs`. 

Start beaker again and you should have the IPFS plugin running.

**Comment by jakobvarmose** [comment]
When installing the progress icon kept spinning even though I could see it had finished in the terminal. So I shut beaker down and when I restarted it, it was working

**Comment by pfrazee** [comment]
Hmm! Ok, glad it worked in the end. I'll poke at the installer a bit more.

So, you can navigate IPFS now?

**Comment by jakobvarmose** [comment]
Yes

**Comment by pfrazee** [comment]
@jakobvarmose ok good. Thanks for tolerating these bugs with me.
