### ISSUE TITLE
Add directory-listing to IPFS views when no index.html is present

### ISSUE THREAD

**Issue by jakobvarmose** [pfrazee/beaker#66]
Go to this URL:
ipfs:/ipfs/QmW1bhojT2TEqMzmRvpKQhHKBPfBv84Mvra3RporfczFec
You will receive the error "This site cant be reached"

I would expect to see something like on the ipfs gateway:
https://ipfs.io/ipfs/QmW1bhojT2TEqMzmRvpKQhHKBPfBv84Mvra3RporfczFec

**Comment by pfrazee** [comment]
Yep, this has been a todo

**Comment by pfrazee** [comment]
Done
