### ISSUE TITLE
audio player cannot be accessed 

### ISSUE THREAD

**Issue by fredhampton** [pfrazee/beaker#76]
I added an mp3 file to dat site.
When the dat link is clicked on the music player is out of reach in the upper left hand corner of the browsing window

**Comment by pfrazee** [comment]
Thanks for the report. What's your OS and Beaker version?

**Comment by fredhampton** [comment]
Mac OSX developer beta 
Latest Beaker Version via git clone from github



 

On September 3, 2016 at 11:39:31 AM, Paul Frazee (notifications@github.com) wrote:

Thanks for the report. What's your OS and Beaker version?

**Comment by pfrazee** [comment]
Ok, issue confirmed & reproduced. Thanks for reporting. Adding to the 0.3.1 milestone.

**Comment by pfrazee** [comment]
There are inline styles which are applied on the audio player. (Probably on the video player as well.) Due to the Content-Security-Policies that Dat uses to serve assets, these styles are failing to apply.

Ideal solution: Add an API to Electron to control the User Agent Styles. This will take some time, so we should put it on the todo-list for now.

Temporary solution: detect when the page is fullscreen video/audio and use `.insertCSS()` to fix the styles.

**Comment by fredhampton** [comment]
Thanks !!!!
Where would we add the .insertCSS()  ?

 

On September 3, 2016 at 4:24:49 PM, Paul Frazee (notifications@github.com) wrote:

There are inline styles which are applied on the audio player. (Probably on the video player as well.) Due to the Content-Security-Policies that Dat uses to serve assets, these styles are failing to apply.

Ideal solution: Add an API to Electron to control the User Agent Styles. This will take some time, so we should put it on the todo-list for now.

Temporary solution: detect when the page is fullscreen video/audio and use .insertCSS() to fix the styles.

**Comment by pfrazee** [comment]
I'll need to dig around for a reliable way to detect when the player is being used. Shouldn't be too hard, but I'll need to throw in some console.logs and experiment a bit.

**Comment by fredhampton** [comment]
Thanks !

 

On September 4, 2016 at 10:57:39 AM, Paul Frazee (notifications@github.com) wrote:

I'll need to dig around for a reliable way to detect when the player is being used. Shouldn't be too hard, but I'll need to throw in some console.logs and experiment a bit.

**Comment by pfrazee** [comment]
Solved in https://github.com/pfrazee/beaker/commit/31b93b548222f38f3785c50529f3976342cdf4bc
