### ISSUE TITLE
support OSX OPEN_URL and protocols

### ISSUE THREAD

**Issue by poga** [pfrazee/beaker#77]
Operation System:
OSX 10.11.6
Beaker Version:
Beaker 0.3

I want to use beaker as my default browser. Currently, it's not possible since it doesn't support "http" and "https" protocol.

`electron-builder` have [built-in support](https://github.com/electron-userland/electron-builder/blob/91addfe4f382059a60fbbd60c2de5aa55d0c42b6/docs/Options.md) for protocol settings. I can try to make a PR for this.

what do you think?

**Comment by pfrazee** [comment]
Good idea! We should see what kind of experience electron-builder gives us. If it feels really good, then let's do it.

We should also add a tool to the settings page for registering the protocols, after installation.

**Comment by pfrazee** [comment]
Adding to milestone 0.3.1
