### ISSUE TITLE
Beaker does not open "view in itunes" link

### ISSUE THREAD

**Issue by fredhampton** [pfrazee/beaker#81]
Mac OSX developer beta 
Latest Beaker Version via git clone from github

I went to https://itunes.apple.com/us/album/experience-hendrix-best-jimi/id344799413
Clicked the "View in iTunes" link and received the following error

"This site cant be reached

The itmss: protocol is not installed

**Comment by pfrazee** [comment]
Thanks for the report. This was already on my todo list, so I'll hit it sometime today.

**Comment by fredhampton** [comment]
Thanks!
Just cloned the latest version.
How do I add a file so that it is shared with dat ?
The previous version had drag and drop 


 

On September 5, 2016 at 9:37:54 AM, Paul Frazee (notifications@github.com) wrote:

Thanks for the report. This was already on my todo list, so I'll hit it sometime today.

**Comment by pfrazee** [comment]
> Just cloned the latest version.
How do I add a file so that it is shared with dat ?
The previous version had drag and drop 

I removed that to simplify some development choices. When the Dat Web API is added (should be in 0.4.0) then we'll be able to make web apps that build Dats, in the same way. (If you're curious, I can go in more depth as to why I removed this feature.)

In the meantime, use the http://dat-data.com/ commandline tool. Once it's installed, just go into the directory you want to share and run `dat .`. If you have any trouble with this, let me know and I'll help you out.

**Comment by fredhampton** [comment]
I am of course curious ;-)
One of the things that attracted me to beaker was how easy it was to drag and drop a file into browser and to the be able to share the link with another beaker user. 

 

On September 5, 2016 at 10:07:44 AM, Paul Frazee (notifications@github.com) wrote:

Just cloned the latest version.
How do I add a file so that it is shared with dat ?
The previous version had drag and drop

I removed that to simplify some development choices. When the Dat Web API is added (should be in 0.4.0) then we'll be able to make web apps that build Dats, in the same way. (If you're curious, I can go in more depth as to why I removed this feature.)

In the meantime, use the http://dat-data.com/ commandline tool. Once it's installed, just go into the directory you want to share and run dat .. If you have any trouble with this, let me know and I'll help you out.

**Comment by pfrazee** [comment]
> I am of course curious ;-)
One of the things that attracted me to beaker was how easy it was to drag and drop a file into browser and to the be able to share the link with another beaker user. 

That's good to know - you're the 2nd person to say so!

Here's why I did it: I removed it to simplify the interactions between the `dat` tool and Beaker. It can be confusing to know which tool you should use, and why. There are subtle differences, and I hate subtle differences. (Subtle differences often mean, complexity!) So I figured: I'll make it simple. I'll say the `dat` tool is what you use to create new dat sites, and Beaker is only the browser. You create with dat, you consume with Beaker.

But, given your (and others') responses, I'm inclined to think I made the wrong choice. The convenience of using drag/drop may outweigh the complexity of having 2 competing solutions. So, your vote: restore the drag/drop?

**Comment by fredhampton** [comment]
I would vote to restore the drag and drop !!!
My partner who is non technical created dat in beaker !!!
I told her to email me the link to her dat and I could then have access to it.
She understood how to do this and it all worked.
I can use the dat cl tool but a majority of possible users cannot and i think going to the dat site to create a dat actually breaks the flow of usage
My partner seem to understand that if you could create dats in beaker you could also consumer dats in beaker.




 

On September 5, 2016 at 10:53:07 AM, Paul Frazee (notifications@github.com) wrote:

I am of course curious ;-)
One of the things that attracted me to beaker was how easy it was to drag and drop a file into browser and to the be able to share the link with another beaker user.

That's good to know - you're the 2nd person to say so!

Here's why I did it: I removed it to simplify the interactions between the dat tool and Beaker. It can be confusing to know which tool you should use, and why. There are subtle differences, and I hate subtle differences. (Subtle differences often mean, complexity!) So I figured: I'll make it simple. I'll say the dat tool is what you use to create new dat sites, and Beaker is only the browser. You create with dat, you consume with Beaker.

But, given your (and others') responses, I'm inclined to think I made the wrong choice. The convenience of using drag/drop may outweigh the complexity of having 2 competing solutions. So, your vote: restore the drag/drop?

**Comment by pfrazee** [comment]
Alright, I'm convinced. I'll restore it!

**Comment by fredhampton** [comment]
:-)!

 

On September 5, 2016 at 11:28:19 AM, Paul Frazee (notifications@github.com) wrote:

Alright, I'm convinced. I'll restore it!

**Comment by pfrazee** [comment]
@fredhampton The master branch has its site-creator restored! You can try it out there after building from source. (Don't forget to update node modules, and you may need to rebuild.) I'll put together the 0.3.1 binaries by the end of the week, and it will include the drag & drop.

**Comment by fredhampton** [comment]
Thanks so much !

 

On September 6, 2016 at 9:09:24 AM, Paul Frazee (notifications@github.com) wrote:

@fredhampton The master branch has its site-creator restored! You can try it out there after building from source. (Don't forget to update node modules, and you may need to rebuild.) I'll put together the 0.3.1 binaries by the end of the week, and it will include the drag & drop.

**Comment by fredhampton** [comment]
Testing the add new site feature. When I add a new site for some reason manifest.json is part of my site 
I attached a screen grab

Thanks 
 

On September 6, 2016 at 9:09:24 AM, Paul Frazee (notifications@github.com) wrote:

@fredhampton The master branch has its site-creator restored! You can try it out there after building from source. (Don't forget to update node modules, and you may need to rebuild.) I'll put together the 0.3.1 binaries by the end of the week, and it will include the drag & drop.

**Comment by pfrazee** [comment]
Yeah, that contains the title and description of your site. Let's open a separate issue for that: https://github.com/pfrazee/beaker/issues/86

**Comment by fredhampton** [comment]
The new look and flow of add sites is great !!!!

 

On September 6, 2016 at 11:15:10 AM, Paul Frazee (notifications@github.com) wrote:

Yeah, that contains the title and description of your site. Let's open a separate issue for that: #86

**Comment by pfrazee** [comment]
Great! Glad you like it. Please keep opening any issues or feature requests
you have!
