### ISSUE TITLE
`New Site` Button doesn't work

### ISSUE THREAD

**Issue by poga** [pfrazee/beaker#88]
Operation System:
OSX 10.11.6

Beaker Version:
0.3.1

When clicking the "New Site" button on `beaker:sites`. The following error occured:

`Uncaught TypeError: datInternalAPI.createNewArchive is not a function`

**Comment by pfrazee** [comment]
Hey @poga, are you building from source? If so, did you remember to run `npm install`? If so, you might also try running `npm run rebuild`.

**Comment by poga** [comment]
Yea, I forgot to run `npm install`. It works now. Sorry!

**Comment by pfrazee** [comment]
No worries, that gets me all the time too
