### ISSUE TITLE
navbar location input act incorrectly when using Chinese IME input.

### ISSUE THREAD

**Issue by poga** [pfrazee/beaker#97]
Operation System:
OSX 10.11.6
Beaker Version:
0.3.2

When typing in Chinese IME, we need to press `<Enter>` to complete a composition. For Example: 
![2016-09-21 4 11 06](https://cloud.githubusercontent.com/assets/8631/18687208/9351ce4c-7fb1-11e6-9275-6ee7e5716e4d.png)

There are two issues in the screenshot.

1. In the screenshot, the composition is not complete.(You can see there's a line under the characters.) Pressing `<Enter>` means I'm confirming the composition is correct, not for submitting the input.
However, `onKeyUp` will be triggered and submit the input, which is incorrect. 

2. The autocomplete suggestion is wrong. My input is `中文`, but autocomplete is based on `ㄓㄨㄥ` which is a partial input of pre-composition Mandarin Phonetic Symbols(Zhuyin).

I can try to put together a PR for this since this is usually hard to notice for non-IME users.

**Comment by pfrazee** [comment]
> I can try to put together a PR for this since this is usually hard to notice for non-IME users.

Please do! I don't have any experience with this.

**Comment by poga** [comment]
I've tracked down the second issue to this line: https://github.com/pfrazee/beaker/blob/master/app/shell-window/ui/navbar.js#L250 . The regex removed all non-English character so the autocomplete doesn't work.

Can you elaborate the purpose of this regex? If it's for sanitizing the input for DOM, maybe we can use `createTextNode`. If it's for URL escaping, maybe `encodeURIComponent` will be a better option.

**Comment by pfrazee** [comment]
Yeah, follow the `searchTerms` through their usage: they go into
`decorateResultMatches()`, which is a method to highlight (make bold) the
matching terms in the search results.

The rules of that regex are meant to match the rules used in the history
search, which is invoked at
https://github.com/pfrazee/beaker/blob/master/app/shell-window/ui/navbar.js#L466,
and then implemented at
https://github.com/pfrazee/beaker/blob/master/app/background-process/dbs/history.js#L98
.

So, I believe the line you linked shouldn't be enough to cause this
problem, alone. The search() API is what actually generates the
autocomplete results.

**Comment by poga** [comment]
I see. The regex matched all non-English characters inside `autocompleteCurrentValue`, so `searchTerms` becomes `[]`. 

Therefore, an exception is thown at https://github.com/pfrazee/beaker/blob/master/app/shell-window/ui/navbar.js#L327 since `searchTerm` is `undefined`.

```
beaker:shell-window.js:622 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at decorateResultMatches (beaker:shell-window.js:622:25)
    at results.forEach.r (beaker:shell-window.js:545:24)
    at Array.forEach (native)
    at handleAutocompleteSearch (beaker:shell-window.js:545:11)
```

The autocomplete shows the correct input with Chinese IME if I remove the regex.

However, The history API is not returning any result since sqlite don't have built-in tokenizer for non-english words.

**Comment by pfrazee** [comment]
Ok, I'll do some research tomorrow to see if there's an better tokenizer
available for SQLite.

**Comment by poga** [comment]
Sorry, nvm. The history API is working fine. I  searched for something not in the history :p.

I've put together a PR for this issue. Glad to fix any problem you found on it.
https://github.com/pfrazee/beaker/pull/98

Thanks for helping! 👍
