### ISSUE TITLE
dat link uri 

### ISSUE THREAD

**Issue by fredhampton** [pfrazee/beaker#99]
Operation System:OSX 
Beaker Version:Latest from master

When I add the link provide by beaker to the file I m sharing to dat.land it does not work. I receive a page that has broker images.

If I strip out dat:// from the link and only use the number dat.land finds the file 

Is the link provided by beaker with dat:// correct ?

Thanks

**Comment by pfrazee** [comment]
The link is correct. Dat.land needs to be updated to support the `dat://` links. Please file an issue with them! https://github.com/datproject/dat.land/issues
